
--function Craft:convertLabels2Routes()
--    for i,label in ipairs(self.fit_flights[#self.fit_flights].labels) do
--        if #label > 2 then 
--            local route = {cost = label.cost, craft = self.id}
--            for i=2,#label-1 do 
--                route[#route+1] = self.fit_flights[label[i]]
--            end 
--            routes[#routes+1] = route
--        end 
--    end
--    for i=1,#self.fit_flights do self.fit_flights[i].labels = {} end
--end 

--function Craft:generateRoute()
--    for i,node1 in ipairs(self.fit_flights) do
--        for _,label in ipairs(node1.labels) do
--            for _,node_id in ipairs(node1.adj) do 
--                label:extendNode(node1, self.fit_flights[node_id])  
--            end 
--        end
--    end
--    self:convertLabels2Routes()
--end  